# theme            = "cnl"
theme            = "cnl-spirit"
# baseurl          = "http://cnl-naturopathie.ch/"
# baseurl          = "http://nicocnl.s3-website-eu-west-1.amazonaws.com/"
baseurl          = "http://pausenaturo.com/hugo_output/"
canonifyurls     = true
languageCode     = "fr-fr"
title            = "CNL-Naturopathie"
disableRSS       = true
[params]
    Webmaster          = '<a href="mailto:nicolas.jeanmonod@bluewin.ch">Nicolas Jeanmonod</a>'
    CopyrightHTML      = "© CNL Naturopathie Lausanne"
